const GIFS = {
  LOADING: 'GIFS_LOADING',
  FETCH_SUCCESS: 'GIFS_FETCH_SUCCESS',
  FETCH_FAILED: 'GIFS_FETCH_FAILED',
  FETCH_SEARCH_SUCCESS: 'GIFS_FETCH_SUCCESS_SEARCH',
  FETCH_SEARCH_FAILED: 'GIFS_FETCH_FAILED_FAILED'
};

export { GIFS };
